language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "4"
  - "5"
  - "6"
env:
  - WEBPACK=webpack@1
before_install:
  - stty columns 120
install:
  - npm install --ignore-scripts
  - npm rm webpack
  - npm install $WEBPACK --ignore-scripts || true
script:
  - npm test
